# Generated by Django 6.0.3 on 2026-03-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='db.guild'),
        ),
    ]
